### PR TITLE
Updated SIBER

### PR DESCRIPTION
**Pull request by andrewcparnell**
Changed a few things around very slightly. It now compiles and runs for me. The trick is to do this at the command line:
`R CMD build SIBER`
which should be very quick, then
`R CMD check --as-cran SIBER_2.0.tar.gz`
which will go through and now give no notes or warnings.

I ran through the vignette and all the code worked there.

Andrew

### CODE REVIEW

**Comment by AndrewLJackson** [comment]
Awesome thanks

I will take a look later when I get home. Doing some recreational coding on my holidays! But only while abi isn't looking!

I think building via Rstudio has some quirks. Will stick with devtools directly for now

Roxygen code goes in the top of the .R files. It then uses this to write the .Rmd files in /man

It also writes the NAMESPACE file automatically. 

But a few people I've talked to reckon it's a bit too smart for its own good sometimes. 

Cheers. Looking forward to checking out your updates

Andrew

**Comment by AndrewLJackson** [comment]
hi andrew

I've been checking through your changes and have made them manually in my
own branch, as you were working off my older master branch. I have been
working on the camelCase branch to bring the function names in line with
Google Style guide.

NB !! ******************************
Could you try this specific branch again please?
https://github.com/AndrewLJackson/SIBER/tree/camelCase-rename
************************************


I still can't get it to pass the the checks, and I can't for the life of me
see what change you made that meant that the four missing functions
plotCommunityHulls, plotGroupEllipses, plotGroupHulls, plotSiberObject now
get included.

Ive just checked and they are being created under R CMD build SIBER and are
being put into the tar.gz folder that is created above my project folder,
so its obviously a problem during package checking.

They are exported in NAMESPACE and their names match their function and
file names and i just can't work out why they are the only functions not
being moved into the SIBER.Rcheck/R folder along with their corresponding
documentation files.

I have some other odds things going on that i can't reconcile

My data folder keeps being removed as an empty folder, when there is a file
demo.siber.data.rda in there along with a corresponding documentation file
in man/. Again this is being created in under the package build, but gets
lost during checking.

My external data folder inst/extdata which contains a *.csv file which i
want bundled.. but it keeps getting canned too. Again this is being created
in under the package build, but gets lost during checking.

My vignette compiles nicely, so clearly all my data and functions are
appropriately named in my Rstudio project and something is happening during
checking.

any guesses?

cheers
andrew

On 12 August 2015 at 11:33, Andrew Parnell <notifications@github.com> wrote:

> R CMD check --as-cran SIBER_2.0.tar.gz




-- 
*You can now follow SIAR on Facebook
<http://www.facebook.com/pages/SIAR-Stable-Isotope-Analysis-in-R/148501811896914>
or
try my video podcasts
<http://www.tcd.ie/Zoology/research/research/theoretical/Rpodcasts.php> for
R

Dr Andrew Jackson
Assistant Professor
School of Natural Sciences
Director of the Trinity Centre for Biodiversity Research
Zoology Building, Trinity College Dublin, Dublin 2, Ireland
Tel. + 353 1 896 2728, Fax. + 353 1 677 8094, Email. a.jackson@tcd.ie,
Twitter: @yodacomplex <https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

**Comment by AndrewLJackson** [comment]
i think i might be close to getting it to pass the checks

dont do anything about my last email just yet! will let you know either way.

.. and just some additional notes

based on advice from Wickham, i don't import any packages or libraries in
the NAMESPACE file. Instead i call the functions they require directly (as
you also added) in my functions using e.g. rjags::coda.samples() or
hdrcde:hdr() etc...



On 12 August 2015 at 17:13, Andrew Jackson <a.jackson@tcd.ie> wrote:

> hi andrew
>
> I've been checking through your changes and have made them manually in my
> own branch, as you were working off my older master branch. I have been
> working on the camelCase branch to bring the function names in line with
> Google Style guide.
>
> NB !! ******************************
> Could you try this specific branch again please?
> https://github.com/AndrewLJackson/SIBER/tree/camelCase-rename
> ************************************
>
>
> I still can't get it to pass the the checks, and I can't for the life of
> me see what change you made that meant that the four missing functions
> plotCommunityHulls, plotGroupEllipses, plotGroupHulls, plotSiberObject now
> get included.
>
> Ive just checked and they are being created under R CMD build SIBER and
> are being put into the tar.gz folder that is created above my project
> folder, so its obviously a problem during package checking.
>
> They are exported in NAMESPACE and their names match their function and
> file names and i just can't work out why they are the only functions not
> being moved into the SIBER.Rcheck/R folder along with their corresponding
> documentation files.
>
> I have some other odds things going on that i can't reconcile
>
> My data folder keeps being removed as an empty folder, when there is a
> file demo.siber.data.rda in there along with a corresponding documentation
> file in man/. Again this is being created in under the package build, but
> gets lost during checking.
>
> My external data folder inst/extdata which contains a *.csv file which i
> want bundled.. but it keeps getting canned too. Again this is being created
> in under the package build, but gets lost during checking.
>
> My vignette compiles nicely, so clearly all my data and functions are
> appropriately named in my Rstudio project and something is happening during
> checking.
>
> any guesses?
>
> cheers
> andrew
>
> On 12 August 2015 at 11:33, Andrew Parnell <notifications@github.com>
> wrote:
>
>> R CMD check --as-cran SIBER_2.0.tar.gz
>
>
>
>
> --
> *You can now follow SIAR on Facebook
> <http://www.facebook.com/pages/SIAR-Stable-Isotope-Analysis-in-R/148501811896914> or
> try my video podcasts
> <http://www.tcd.ie/Zoology/research/research/theoretical/Rpodcasts.php>
> for R
>
> Dr Andrew Jackson
> Assistant Professor
> School of Natural Sciences
> Director of the Trinity Centre for Biodiversity Research
> Zoology Building, Trinity College Dublin, Dublin 2, Ireland
> Tel. + 353 1 896 2728, Fax. + 353 1 677 8094, Email. a.jackson@tcd.ie,
> Twitter: @yodacomplex <https://twitter.com/yodacomplex>
> http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php
>



-- 
*You can now follow SIAR on Facebook
<http://www.facebook.com/pages/SIAR-Stable-Isotope-Analysis-in-R/148501811896914>
or
try my video podcasts
<http://www.tcd.ie/Zoology/research/research/theoretical/Rpodcasts.php> for
R

Dr Andrew Jackson
Assistant Professor
School of Natural Sciences
Director of the Trinity Centre for Biodiversity Research
Zoology Building, Trinity College Dublin, Dublin 2, Ireland
Tel. + 353 1 896 2728, Fax. + 353 1 677 8094, Email. a.jackson@tcd.ie,
Twitter: @yodacomplex <https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

**Comment by AndrewLJackson** [comment]
hi again

after all that, it looks like I'm sorted. Deleted all the previously builds
and using R CMD seems to be much better than Rstudio still

got it through with no errors, and only two notes, one of which is that
this is a new submission. The other note relates to me not importing the
dependent package functions, but since I'm calling directly then i think it
should be fine, and certainly i won't get any "excessive package loading"
threats from CRAN.

fingers crossed it passes their own scrutiny!

thanks for all the help

andrew

On 12 August 2015 at 17:13, Andrew Jackson <a.jackson@tcd.ie> wrote:

> hi andrew
>
> I've been checking through your changes and have made them manually in my
> own branch, as you were working off my older master branch. I have been
> working on the camelCase branch to bring the function names in line with
> Google Style guide.
>
> NB !! ******************************
> Could you try this specific branch again please?
> https://github.com/AndrewLJackson/SIBER/tree/camelCase-rename
> ************************************
>
>
> I still can't get it to pass the the checks, and I can't for the life of
> me see what change you made that meant that the four missing functions
> plotCommunityHulls, plotGroupEllipses, plotGroupHulls, plotSiberObject now
> get included.
>
> Ive just checked and they are being created under R CMD build SIBER and
> are being put into the tar.gz folder that is created above my project
> folder, so its obviously a problem during package checking.
>
> They are exported in NAMESPACE and their names match their function and
> file names and i just can't work out why they are the only functions not
> being moved into the SIBER.Rcheck/R folder along with their corresponding
> documentation files.
>
> I have some other odds things going on that i can't reconcile
>
> My data folder keeps being removed as an empty folder, when there is a
> file demo.siber.data.rda in there along with a corresponding documentation
> file in man/. Again this is being created in under the package build, but
> gets lost during checking.
>
> My external data folder inst/extdata which contains a *.csv file which i
> want bundled.. but it keeps getting canned too. Again this is being created
> in under the package build, but gets lost during checking.
>
> My vignette compiles nicely, so clearly all my data and functions are
> appropriately named in my Rstudio project and something is happening during
> checking.
>
> any guesses?
>
> cheers
> andrew
>
> On 12 August 2015 at 11:33, Andrew Parnell <notifications@github.com>
> wrote:
>
>> R CMD check --as-cran SIBER_2.0.tar.gz
>
>
>
>
> --
> *You can now follow SIAR on Facebook
> <http://www.facebook.com/pages/SIAR-Stable-Isotope-Analysis-in-R/148501811896914> or
> try my video podcasts
> <http://www.tcd.ie/Zoology/research/research/theoretical/Rpodcasts.php>
> for R
>
> Dr Andrew Jackson
> Assistant Professor
> School of Natural Sciences
> Director of the Trinity Centre for Biodiversity Research
> Zoology Building, Trinity College Dublin, Dublin 2, Ireland
> Tel. + 353 1 896 2728, Fax. + 353 1 677 8094, Email. a.jackson@tcd.ie,
> Twitter: @yodacomplex <https://twitter.com/yodacomplex>
> http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php
>



-- 
*You can now follow SIAR on Facebook
<http://www.facebook.com/pages/SIAR-Stable-Isotope-Analysis-in-R/148501811896914>
or
try my video podcasts
<http://www.tcd.ie/Zoology/research/research/theoretical/Rpodcasts.php> for
R

Dr Andrew Jackson
Assistant Professor
School of Natural Sciences
Director of the Trinity Centre for Biodiversity Research
Zoology Building, Trinity College Dublin, Dublin 2, Ireland
Tel. + 353 1 896 2728, Fax. + 353 1 677 8094, Email. a.jackson@tcd.ie,
Twitter: @yodacomplex <https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

**Comment by andrewcparnell** [comment]
Apologies. I was so excited to be 'forking a repo' that I forgot you'd asked me to look a specific branch!

I would remove that second note if I were you. My guess is that it's to do with the missing importFrom commands in the namespace. They're very strict and they're likely to find other warnings which didn't show up during the R CMD check. It always drives me mad that they do it like this, but that's just the way it is (piano solo).

Andrew

**Comment by AndrewLJackson** [comment]
done thanks. though i will have to wait for CRAN to can it before i can
resubmit the fix. Doubtless they will uncover other heinous crimes too...

On 12 August 2015 at 18:44, Andrew Parnell <notifications@github.com> wrote:

> Apologies. I was so excited to be 'forking a repo' that I forgot you'd
> asked me to look a specific branch!
>
> I would remove that second note if I were you. My guess is that it's to do
> with the missing importFrom commands in the namespace. They're very strict
> and they're likely to find other warnings which didn't show up during the R
> CMD check. It always drives me mad that they do it like this, but that's
> just the way it is (piano solo).
>
> Andrew
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AndrewLJackson/SIBER/pull/7#issuecomment-130387280>.
>



-- 
*You can now follow SIAR on Facebook
<http://www.facebook.com/pages/SIAR-Stable-Isotope-Analysis-in-R/148501811896914>
or
try my video podcasts
<http://www.tcd.ie/Zoology/research/research/theoretical/Rpodcasts.php> for
R

Dr Andrew Jackson
Assistant Professor
School of Natural Sciences
Director of the Trinity Centre for Biodiversity Research
Zoology Building, Trinity College Dublin, Dublin 2, Ireland
Tel. + 353 1 896 2728, Fax. + 353 1 677 8094, Email. a.jackson@tcd.ie,
Twitter: @yodacomplex <https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

**Pull request closed without merging**
